### ISSUE TITLE
example doesn't work in nu 0.87.2

### ISSUE THREAD

**Issue by kurokirasama** [Euphrasiologist/nu_plugin_plot#12]
```bash
let one = (seq 0.0 0.01 20.0 | math sin)
let two = (seq 1.0 0.01 21.0 | math sin)

$one | plot
[$one $two] | plot
```

They both give this error:
```
Error:   × Plugin failed to encode
  help: missing field `span` at line 1 column 278
  ```

**Comment by Euphrasiologist** [comment]
I'll have to investigate further. Are you executing this as a single script?

Also, what's your nu and plug-in versions?

**Comment by Euphrasiologist** [comment]
Also I realise that `math sin` is now an extra feature when building nushell.

**Comment by kurokirasama** [comment]
is working now in latest version of the repo
