### ISSUE TITLE
error in nushell 0.92.2

### ISSUE THREAD

**Issue by kurokirasama** [Euphrasiologist/nu_plugin_plot#17]
```nu
Plugin `plot` read error: Plugin failed to load: Plugin is compiled for nushell version 0.91.0, which is not compatible with version 0.92.2
Error:   × Error getting signatures
   ╭─[source:1:1]
 1 │ register /home/kira/.cargo/bin/nu_plugin_plot
   · ────┬───
   ·     ╰── Plugin failed to load: Plugin `plot` is compiled for nushell version 0.91.0, which is not compatible with version 0.92.2
   ╰────
```

**Comment by Euphrasiologist** [comment]
Yes I suspect the plug-in needs to be updated to the new API. Any pointers @fdncred appreciated - I've got less time to update these nowadays!

**Comment by fdncred** [comment]
> Yes I suspect the plug-in needs to be updated to the new API. Any pointers @fdncred appreciated - I've got less time to update these nowadays!

If you look in my repos, for nu_plugin* you'll see a bunch that i've already ported to 0.92.2 https://github.com/fdncred?tab=repositories&q=nu_plugin&type=&language=&sort=

**Comment by lysogeny** [comment]
I have opened #18 to address this.

**Comment by Euphrasiologist** [comment]
Thanks @lysogeny for your work on this. Done some tests on my machine and all looks good!
