### ISSUE TITLE
new plugin signature

### ISSUE THREAD

**Issue by fdncred** [Euphrasiologist/nu_plugin_plot#3]
Head's up. Nushell 0.75.1 just landed some enhancements for plugins.

1. We need to use `PluginSignature` vs `Signature` and use `nu_protocol::PluginSignature`
2. We need to use `PluginExample` if you want examples in your plugin

This is an example of how I've used this in a plugin I'm working on called nu_plugin_dbg
```rust
    fn signature(&self) -> Vec<PluginSignature> {
        vec![PluginSignature::build("dbg")
            .usage("View dbg results")
            .category(Category::Experimental)
            .plugin_examples(vec![PluginExample {
                description: "View dbg results in a pipeline".into(),
                example: "ls | dbg | get name | dbg".into(),
                result: None,
            }])]
    }
```

**Comment by Euphrasiologist** [comment]
Brilliant, thank you for the heads up - will update from this end :)
