### ISSUE TITLE
Install fails because `nu-plugin` and `nu-protocol` are looking for non-existent local paths

### ISSUE THREAD

**Issue by IndigoLily** [Euphrasiologist/nu_plugin_plot#8]
The `nu-plugin` and `nu-protocol` dependencies are looked for in a sibling of this crate's directory:

https://github.com/Euphrasiologist/nu_plugin_plot/blob/5d3a7339123f807a97804b7b2264398faec2e68a/Cargo.toml#L11-L12

But the install instructions say nothing about this.

**Comment by Euphrasiologist** [comment]
You're totally right. I think this was added from a contributor with a pull request, clearly didn't spot that! Thanks.
